package com.adidas.shoetracing.api;

import com.adidas.shoetracing.model.ProductInformation;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class ProductMock {

  public static List<ProductInformation> getMockProducts() {
    return Stream.of(
        buildProduct("IaYCN0aA8I", "Remade Ultraboost", "180€", "ULTRABOOST Comfortable and responsive, Ultraboost became our first shoe to be as popular in day-to-day style as it is in performance running.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/5af87561ea814ed2a6ecadf9008b4c93_9366/Ultraboost_Made_To_Be_Remade_Shoes_Black_GY0363_01_standard.jpg", "", ""),
        buildProduct("iRGyCPBZ6C", "Remade Terrex Free Hiker", "250€", "The TERREX Free Hiker Made To Be Remade lets you be part of a circular product cycle. Wear your gear, return it and we will clean, grind and remake your shoe into something new.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/adcdd2aadae248439ee4ad590104761c_9366/TERREX_FREE_HIKER_MADE_TO_BE_REMADE_White_S29049_01_standard.jpg", "", ""),
        buildProduct("dS1GJ2odQB", "Remade Stan Smith", "180€", "The adidas Stan Smith has been doing it for decades. First on the tennis courts and then in closets around the world. This pair takes the impact a step further.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c9b1907b3e6544f3b71ead5100ed7aa0_9366/Stan_Smith_Made_To_Be_Remade_Shoes_White_GY3020_01_standard.jpg", "", ""),
        buildProduct("8ycROdzvIs", "Remade Training Tee", "55€", "When you're finished with this adidas tee, someone thousands of miles away will get a chance to wear it when it's remade into something else. That means the positive vibe you're putting out right now as you wear it in yoga class might travel clear across the globe. Meditate on that for a minute.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/0782a98d442a4fcc94b6ae4c00ebce44_9366/Made_To_Be_Remade_Training_Tee_Green_HB9188_21_model.jpg", "", ""),
        buildProduct("IoM6khIkjp", "Remade Tee", "75€", "Winners choose a winning outfit. adidas athletes wear this tennis t-shirt at the Southern Hemisphere's own major tournament. It's patterned with colourful '90s-style graphics so you stand out on the court.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6d05de695cce4145ab27adfe00c79f64_9366/Tennis_Made_to_Be_Remade_Tee_White_H67123_21_model.jpg", "", ""),
        buildProduct("ZbIBFRDSas", "Remade Training Shorts", "50€", "Dial your workout way down, and do a session of restorative yoga in these adidas shorts. The drawcord-adjustable elastic waist lets you create a fit that's just right for big breaths in and out.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9b6ebfd3a32a466c97c1ae3d00a00d54_9366/Made_To_Be_Remade_Training_Shorts_Black_HE5461_21_model.jpg", "", ""),
        buildProduct("MfgYNGbPI1", "Remade Running Tee", "38€", "Push the pace. This adidas running t-shirt has a lightweight build to help you perform your best. AEROREADY manages your body's moisture to keep you dry and in the zone. The raschel knit elevates your workout look.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/f7d784f91d3f48a592b4adc80156c913_9366/Made_To_Be_Remade_Running_Tee_Pink_HB9231_21_model.jpg", "", ""),
        buildProduct("y6nV4ja4Af", "Remade Running Tank Top", "38€", "Make every run better than the last. This adidas tank top has a raschel knit design that combines fashion with performance to help you feel your best. AEROREADY manages your body's moisture to keep you dry and in the zone.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a492e75b437e4a75ba62add0005ff266_9366/Made_To_Be_Remade_Running_Tank_Top_Green_HB9230_21_model.jpg", "", ""),
        buildProduct("TfD5AeZ8nz", "Remade Tennis Dress", "130€", "Winners choose a winning outfit. Garbiñe Muguruza wears this adidas tennis dress at the Southern Hemisphere's own major tournament. Colourful '90s-style graphics and a swingy pleated skirt stand out on the court. AEROREADY sweeps moisture from the skin to keep you dry and in control.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6d96f3ad4c144a7bba58adfe00cb8424_9366/Tennis_Made_to_Be_Remade_Dress_White_HA7610_21_model.jpg", "", ""),
        buildProduct("5N4qRbuvaI", "Remade Polo Shirt", "65€", "Tee off in sleek style. This adidas golf polo shirt is made of textured jacquard fabric for a soft feel. Side hem vents let you move freely. The longer back hem keeps it tucked in for a clean look. After it sees you through many rounds, send it back and we'll remake it. That's a win for your game and the planet.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4d027f48a0624a0eb944ae00017719a6_9366/Go-To_Made_To_Be_Remade_Polo_Shirt_Red_HE2887_21_model.jpg", "", ""),
        buildProduct("hzQgl9TqDo", "Remade Training Shorts", "50€", "Dial your workout way down, and do a session of restorative yoga in these adidas shorts. The drawcord-adjustable elastic waist lets you create a fit that's just right for big breaths in and out. The shaped leg hem ensures you can lean forward and hold your stretches until your muscles release. ", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/05272888f39149cdbe29ae2101325d5d_9366/Made_To_Be_Remade_Training_Shorts_Green_HE5462_21_model.jpg", "", ""),
        buildProduct("TI6OMhVVwh", "Future Icons Hoodie", "60€", "You put in the time. You put in the effort. And when you put on this adidas sweatshirt after your workout, you feel the reward. Soft cotton material drapes the body in a relaxed shape, so you practically sink into comfort. Ribbed cuffs go ahead and bring an extra level of snug to the casual sweatshirt. Whatever's next on the agenda, you'll show up feeling good.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/f054c9d032c14349b97ead240166e4db_9366/adidas_Sportswear_Future_Icons_Hoodie_White_H24083_21_model.jpg", "", ""),
        buildProduct("o2MVCv5oLD", "Pride Hoodie", "75€", "This adidas hoodie boldly celebrates the warmth we give to and take from our communities.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3ad35c912fae4d2eb68fadca007ba772_9366/Pride_Hoodie_(Gender_Neutral)_Black_HC4451_21_model.jpg", "", ""),
        buildProduct("rH9RSmgwZf", "Trefoil Trucker Cap", "23€", "One icon meets another in this classic trucker cap. A large embroidered Trefoil logo takes centre stage above the slightly curved brim. Built in soft cotton with traditional mesh panels, it adjusts with a snapback closure.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ed057b796ab64667b14da9200129aa20_9366/Trefoil_Trucker_Cap_Black_DV0170_01_standard.jpg", "", ""),
        buildProduct("QP0ZGhw2aA", "Baseball Cap", "20€", "Top things off nicely with this classic Baseball Cap. Made with sunny days in mind, the soft fabric shields you from the sun's rays. An adidas Badge of Sport takes centre stage in front.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/93c18452f7b246ada981aa8700a45834_9366/Baseball_Cap_Black_FK0891_01_standard.jpg", "", ""),
        buildProduct("ZDKcHu8jrt", "Tiro Parka", "100€", "Track top? Check. Club jersey? Naturally. Inspired by super casual football fan culture, this adidas Tiro Parka offers an extra layer when it's time to hit the road. The lined, high-collar hood and long length work together for all-day coverage. A drawcord at the back lets you adjust the fit to find the perfect look. Side pockets integrated into the design let you keep your travel essentials close.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/0d2d29f599334f26a5a1ae2100fdd650_9366/Tiro_Parka_Purple_HF8393_21_model.jpg", "", ""),
        buildProduct("IxzLv4Cd79", "Five Ten All Mountain Rain Jacket", "220€", "Through cool misty mornings or afternoon showers, the adidas Five Ten All-Mountain Rain Jacket keeps you dry and on the bike. RAIN.RDY keeps out wind and rain, while elastic cuffs, hem and hood further seal out the elements while you ride. Its lightweight build makes for easy packing. Zip out the showers and keep on riding.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/38e9722ac81d4bab83bfac9f00ee45f1_9366/Five_Ten_All-Mountain_Rain_Jacket_Black_GJ8423_21_model.jpg", "", ""),
        buildProduct("7vPE4bx6my", "Classics Beckenbauer Track Pants", "65€", "The 3-Stripes have been a symbol of sport for generations. But you don't need to be on the track or the pitch to wear them proudly. Settle into the comfort of these adidas track pants and go at your own speed. Walks in the park and lazy days are a good fit. The pants are also made with recycled materials. Wherever you wear them, you'll feel good in more ways than one.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8db86f7c0519410a9fbaad22011527fd_9366/Adicolor_Classics_Beckenbauer_Primeblue_Track_Pants_Black_H09115_21_model.jpg", "", ""),
        buildProduct("ypZrWqY77v", "Classics Woven Back Cuff Jogers", "70€", "Some could say the baggier, the better. Pull on these adidas joggers and you tell us. They've got that perfect loose fit that creates a slouchy look, strongly emphasised with the stretchy elastic waist and cuffs. The classic sport style practically demands crop top or bodysuit action, but the best thing about these is that their versatility lets you play them up or down however you're feeling that day.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/1f67477ade854923ba83adc100ab8f74_9366/Adicolor_Classics_Woven_Back_Cuff_Joggers_Purple_HC4546_21_model.jpg", "", ""),
        buildProduct("c5irvL8LrD", "Y-3 TN C1 Shoes", "400€", "The Y-3 TN C1 Shoes experiment with a new approach to comfort, playing with proportions, sensations and inspirations to explore an innovative new concept. Foam padding wraps around the cushioned EVA midsole, which goes beyond the feeling of comfort and creates a cloud-like visual representation of it. The rubber outsole takes inspiration from track and field runners with its spikes aesthetic.", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4950627e37754a71a7dcadf200fcc1ae_9366/Y-3_TN_C1_Shoes_White_GX1087_01_standard.jpg", "", "")
        ).collect(Collectors.toList());
  }

  private static ProductInformation buildProduct(String id, String name, String price, String description, String imageUrl, String owner, String ownerAdress) {
    ProductInformation productInformation = new ProductInformation();
    productInformation.setId(id);
    productInformation.setName(name);
    productInformation.setPrice(price);
    productInformation.setDescription(description);
    productInformation.setImageUrl(imageUrl);
    productInformation.setOwner(owner);
    productInformation.setOwnerAdress(ownerAdress);
    return productInformation;
  }
}
